### ISSUE TITLE
Cron job to clear caches

### ISSUE THREAD

**Issue by mgax** [ndarilek/dokuwiki-sandstorm#10]
Our network of journalists is [using DokuWiki on Sandstorm](https://eic.network/blog/making-a-network) as a knowledge base, and it's doing a great job! But our wiki has grown past 7GB even tough it mostly contains text.

I've checked on another, smaller wiki grain: after downloading and unpacking the zip file, out of 524MB total size, the `data/lib/dokuwiki/data/cache` folder takes up 508MB. The DokuWiki documentation suggests [running a cron script](https://www.dokuwiki.org/tips:maintenance#automatic_cleanup_script) to remove old files.

**Comment by ndarilek** [comment]
Caches should now be cleaned on launch, with content older than 30 days removed. Hopefully this is large enough to be useful but small enough to keep grain sizes manageable.

I'll probably push another release with this fix tomorrow. I just pushed one with some other major fixes so would like to let that land first and ensure that nothing is broken.

**Comment by mgax** [comment]
🎉 awesome!

**Comment by mgax** [comment]
> I'll probably push another release with this fix tomorrow. I just pushed one with some other major fixes so would like to let that land first and ensure that nothing is broken.

Did you release to the app market? It still says [Last update: October 26, 2016](https://apps.sandstorm.io/app/nx3dqcmz2sjjz939vkg4847vvxrzqsatqfjrt3ea50z3jac5kv7h) :(

**Comment by ndarilek** [comment]
Yes, it hasn't been approved yet.

**Comment by germakoci** [comment]
@ndarilek cool job on the wiki, any idea when that will be approved and released to the app market?

**Comment by ndarilek** [comment]
No idea, the process is outside my control.

In the meantime, I'm told that 
https://apps.sandstorm.io/?experimental=true is a way to get the update now.

**Comment by germakoci** [comment]
thanks. 

I just updated my wiki on my sandstorm installation from https://apps.sandstorm.io/?experimental=true I closed the wiki grain, I signed out, singe back in and relaunched the wiki. same thing, the old wiki didn't update. maybe the update is valid only if I start new dokuwiki grains ?

**Comment by ndarilek** [comment]
How old is the grain? It will only clear caches that are 30 days old.

Note that I'm just literally copying the code out of Doku's own 
recommendations. Also, as written, their code didn't even work, so I 
tried making some modifications. In particular, the code that checked if 
there were any files in the cache directory failed, so I modified it to 
what I think should check if the directory is empty using `ls`.

If you want to help, you might download a backup of your wiki, run the 
various commands in the cleanup function in launcher.sh, and see if they 
correctly find old files. If they don't, then that needs to be reported 
to the Doku folks.

I'm really not all that knowledgeable about Doku. I just want to package 
all this complexity into Sandstorm so it works, and so I never have to 
worry about it again. Doku requires all sorts of specialized knowledge 
about how to perform upgrades, how to clear caches, etc. and is kind of 
a mess in that regard.

**Comment by germakoci** [comment]
thanks a lot for this work, it really helps. 

now the grain is almost a year old and keep accumulated cache. the thing is that updates seem to be working if I launch new DokuWiki grains, but for grains in existence before your updates, it is not working. (for instance your update on showing the full url to a wiki page don't work with older existing wiki grains)

the back-up of the wiki is not working either, since the grain became too large to back-up, it is freezing the system (almost 8 GB). 

I guess my only option is to migrate content to a new wiki grain and start from there.

**Comment by ndarilek** [comment]
The title/URL issue is a different matter entirely. You have to copy the 
footer.html file from the Sandstorm port into the correct location of 
your wiki, meaning you need to do a backup and restore. I can't do that 
manually because you may have a theme using footer.html and I don't want 
to destroy that. There just isn't a good way using Doku to say "this 
code is core to Doku, and this is a user-specific plugin/template."

Do you have access to the server? If so, you can find the grain 
directory in /opt/sandstorm/var/lib/sandstorm and clear the cache using 
rm. Or you can run the commands in launcher.sh in the filesystem and see 
if they actually work.

**Comment by germakoci** [comment]
thanks for the advice - I'll talk to my colleagues and report back

**Comment by germakoci** [comment]
thanks for the instructions @ndarilek , it worked fine and out of 7.5 GB the dokuwiki grain has now 170 MB and can be backed-up and restored again
