### ISSUE TITLE
Feature Request: Latex packages

### ISSUE THREAD

**Issue by benwinding** [ndarilek/dokuwiki-sandstorm#11]
Hi,

I was wondering if you could include the following dependencies:
   
 `apt-get install texlive-latex-base imagemagick ghostscript`

Then everyone could use the amazing LaTex plugin:

https://www.dokuwiki.org/plugin:latex

Or suggest any work arounds?

Thanks so much for your efforts developing this, it's making a lot of peoples lives easier! :+1: 

Cheers,
Ben

**Comment by ndarilek** [comment]
Unfortunately, I think adding LaTeX and its assorted dependencies would make the app very large, possibly negatively impacting the experiences of anyone *not* wanting this plugin.

I'll leave this issue open for a bit, but for now I'm tending towards no. I don't know what the answer is for folks wanting extra plugins. If it was just a small dependency then I might consider it, but typesetting is huge, not to mention that I'd probably have to blanket include a bunch of macros and other TeX files because the automatic file scanner won't pick them up.

Sorry.

**Comment by benwinding** [comment]
Thanks for the fast response @ndarilek!

That's fair enough, I just looked at those packages and they're way larger than I initially thought, probably not worth it.

It seems that the following plugin does what I need anyway without the huge overhead in dependencies. Just lets you easily write equations in Dokuwiki.

https://www.dokuwiki.org/plugin:mathjax

Thanks,
Ben
