### ISSUE TITLE
DokuWiki ACL are ignored

### ISSUE THREAD

**Issue by pchampin** [ndarilek/dokuwiki-sandstorm#4]
I can invite other users to the wiki, but they all seem to have the rights set for @user in the DokuWiki ACL configuration. I tried different things to grant them other rights (e-mail address or short name), but without any success.

**Comment by ndarilek** [comment]
So a few things here:
1. The grain doesn't know the user's email address, so you can't 
   manipulate users via their email from within the grain. As a matter of 
   fact, since Doku requires an email address, the user database gives 
   everyone a fake address.
2. The Doku username is Sandstorm's user ID, which is an opaque string 
   guaranteed to be unique. Users' display names, which are not guaranteed 
   to be unique, are set every time the user connects from Sandstorm. This 
   lets users change their profile display name from within Sandstorm's 
   interface, then syncs them up with the wiki as soon as possible.
3. The intent of this port isn't that you'll create distinct ACLs. As 
   you've noticed, users get the group @user while admins get @admin. These 
   ACLs are read from Sandstorm's permissions, and are set up by sharing 
   links. I doubt that setting up your own ACLs will work, and that is by 
   design.
4. If you want portions of your wiki to not be accessible to others, my 
   intent was that you'd spin up another wiki. Since Sandstorm makes this a 
   super cheap operation, you'd handle finer-grained ACLs with an entirely 
   separate wiki and manage permissions exclusively via Sandstorm. I 
   recognize that isn't entirely ideal from a more traditional perspective, 
   where everything is hosted in a single app. There's also no way for 
   Sandstorm to push permission changes made in its UI to apps, and I 
   wanted to let Sandstorm handle all of authorization/authentication.

I'd accept patches to resolve these if you have better approaches. I 
myself am not a PHP developer, and only put this together so my 
organization can host its wiki in Sandstorm.

Thanks.

**Comment by pchampin** [comment]
@ndarilek thanks a lot for this detailed answer. Things are much clearer for me now, and I understand that it is not trivial to use Dokuwiki's ACL with Sandstorm users.

I suggest that you update the description of Dokuwiki in the Sandstorm market to make this limitation explicit -- currently, the description actually _advertises_ the ACL functionalities, which is rather misleading...

Unfortunately, I'm not a PHP developer either, so I can't help for a patch :-/ But I'll spread the word, in case I find someone interested ;)

**Comment by ndarilek** [comment]
Thanks for the pointer to the description text, it was lifted directly from the DokuWiki site. I've updated it to remove ACLs and auth backends since neither is applicable to this port.

Closing this for now, since the Sandstorm way for this is probably to create multiple wikis and share them, or to use other apps more suited to whatever is being shared and locked down. I'm open to other possible solutions, but I can't afford to maintain a package that diverges too wildly from upstream. Thanks!
