### ISSUE TITLE
[enhancement] - Markdown plugin

### ISSUE THREAD

**Issue by zeigerpuppy** [ndarilek/dokuwiki-sandstorm#9]
In most Sandstorm applications, markdown appears to be the *lingua franca*,
I have tested the Mardown Extra Plugin and it works well with docuwiki (real time preview and two ways of insertying markdown - in blocks or by naming page `Name.md`).
https://www.dokuwiki.org/plugin:markdownextra

I think it may be a good plugin to include by default.

**Comment by ndarilek** [comment]
I really don't want to start adding custom plugins, especially as 
they'll have to be a thing I have to integrate, upgrade, and ship new 
versions for. I also think there are a few different markdown plugins, 
so then we'll need to debate which to use. And then you have wikis like 
the one I'm migrating which already use a different markdown plugin, 
which means I'll have to remove the new plugin on every run--that, or 
try to migrate 3.5 years of wiki content to a different plugin.

You can add plugins to your own wiki by creating a new instance, taking 
a backup, unzipping the archive, and placing the plugins in the correct 
folder in the archive. I have a rather large wiki with lots of plugins, 
and this method seems to have worked for it. Because there are no 
opinions, you can be guaranteed that if your plugin works with stock 
Doku then it _should_ work with this port, and you'll never hit a 
conflict because I made a choice for you.

**Comment by zeigerpuppy** [comment]
Thanks for the explanation, that's a very reasonable way to do it.
I'm impressed with how well dokuwiki works in sandstorm, good work on the port!
